### ISSUE TITLE
Post-processing static assets fails due to missing font files

### ISSUE THREAD

**Issue by jguthmiller** [mtford90/silk#51]
The file silk/static/silk/lib/bootstrap.min.css references font files that have a relative path that exists outside of the repo. For example:

```
@font-face{font-family:'Glyphicons Halflings';src:url('../../../../../../../Downloads/bootstrap-datetimepicker-2.3.1/sample%20in%20bootstrap%20v3/bootstrap/fonts/glyphicons-halflings-regular.eot'); ...}
```

This causes post-processing to fail since django can't find the file for cache busting (if you're using CachedStaticFilesStorage):

```
Post-processing 'silk/lib/bootstrap.min.css' failed!

Traceback (most recent call last):
  File "./manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle_noargs
    collected = self.collect()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 120, in collect
    raise processed
ValueError: The file 'Downloads/bootstrap-datetimepicker-2.3.1/sample in bootstrap v3/bootstrap/fonts/glyphicons-halflings-regular.eot' could not be found with <pipeline.storage.PipelineCachedStorage object at 0x3191c10>.
```

**Comment by mtford90** [comment]
@jguthmiller I'm working on fixing this up now - am totally changing the way styles/assets are handled so this should be fixed soon

**Comment by fedosov** [comment]
:+1:

**Comment by mtford90** [comment]
This should now be fixed in master, no idea how that happened, probably pycharm messed around with the URLs.
