### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by ianwalter** [mtford90/silk#54]
I'm running Django 1.6.10 and silk 0.4. Here is the trace:

```
Running migrations for silk:
 - Migrating forwards to 0002_auto__add_field_request_pyprofile__add_index_request_start_time.
 > silk:0001_initial
 ! Error found during real run of migration! Aborting.

 ! Since you have a database that does not support running
 ! schema-altering statements in transactions, we have had 
 ! to leave it in an interim state between migrations.

! You *might* be able to recover with:   = DROP TABLE `silk_request` CASCADE; []
   = DROP TABLE `silk_response` CASCADE; []
   = DROP TABLE `silk_sqlquery` CASCADE; []
   = DROP TABLE `silk_profile` CASCADE; []
   = DROP TABLE `silk_profile_queries` CASCADE; []

 ! The South developers regret this has happened, and would
 ! like to gently persuade you to consider a slightly
 ! easier-to-deal-with DBMS (one that supports DDL transactions)
 ! NOTE: The error which caused the migration to fail is further up.
Error in migration: silk:0001_initial
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/ian/.virtualenv/flashnotes/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/ian/.virtualenv/flashnotes/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/ian/.virtualenv/flashnotes/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/ian/.virtualenv/flashnotes/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Users/ian/.virtualenv/flashnotes/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/Users/ian/.virtualenv/flashnotes/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/Users/ian/.virtualenv/flashnotes/lib/python2.7/site-packages/south/migration/migrators.py", line 254, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/Users/ian/.virtualenv/flashnotes/lib/python2.7/site-packages/south/migration/migrators.py", line 329, in migrate_many
    result = self.migrate(migration, database)
  File "/Users/ian/.virtualenv/flashnotes/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/Users/ian/.virtualenv/flashnotes/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/Users/ian/.virtualenv/flashnotes/lib/python2.7/site-packages/south/migration/migrators.py", line 85, in run_migration
    south.db.db.execute_deferred_sql()
  File "/Users/ian/.virtualenv/flashnotes/lib/python2.7/site-packages/south/db/generic.py", line 318, in execute_deferred_sql
    self.execute(sql)
  File "/Users/ian/.virtualenv/flashnotes/lib/python2.7/site-packages/south/db/generic.py", line 282, in execute
    cursor.execute(sql, params)
  File "/Users/ian/.virtualenv/flashnotes/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/ian/.virtualenv/flashnotes/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/Users/ian/.virtualenv/flashnotes/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/Users/ian/.virtualenv/flashnotes/lib/python2.7/site-packages/MySQLdb/cursors.py", line 176, in execute
    if not self._defer_warnings: self._warning_check()
  File "/Users/ian/.virtualenv/flashnotes/lib/python2.7/site-packages/MySQLdb/cursors.py", line 92, in _warning_check
    warn(w[-1], self.Warning, 3)
_mysql_exceptions.Warning: Specified key was too long; max key length is 767 bytes
```

**Comment by mtford90** [comment]
@ianwalter i just disabled south migrations since the way silk handles identifiers just changed dramatically to fix a different bug. I suspect that silk shouldn't include migrations anyhow.
