### ISSUE TITLE
NoReverseMatch: Reverse for 'summary' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

### ISSUE THREAD

**Issue by a1Gupta** [mtford90/silk#74]
I am getting NoReverseMatch error. I tried placing middleware at top but its giving same error.

These are my middleware classes:

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'subdomains.middleware.SubdomainURLRoutingMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social.apps.django_app.middleware.SocialAuthExceptionMiddleware',
    'django_mobile.middleware.MobileDetectionMiddleware',
    'django_mobile.middleware.SetFlavourMiddleware',
)

and its the traceback-

Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/ashish/.virtualenvs/myapp/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 64, in __call__
    return self.application(environ, start_response)
  File "/home/ashish/.virtualenvs/myapp/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 168, in __call__
    self.load_middleware()
  File "/home/ashish/.virtualenvs/myapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 44, in load_middleware
    mw_class = import_string(middleware_path)
  File "/home/ashish/.virtualenvs/myapp/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ashish/.virtualenvs/myapp/local/lib/python2.7/site-packages/silk/middleware.py", line 31, in <module>
    fpath = silky_reverse('summary')
  File "/home/ashish/.virtualenvs/myapp/local/lib/python2.7/site-packages/silk/middleware.py", line 27, in silky_reverse
    r = reverse(name, *args, **kwargs)
  File "/home/ashish/.virtualenvs/myapp/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 551, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/ashish/.virtualenvs/myapp/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 468, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'summary' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[24/Aug/2015 14:15:14] "GET /silk HTTP/1.1" 500 59

Is this error due to middleware placement or its some other issue ?

**Comment by mtford90** [comment]
@a1Gupta apologies for the delay in getting to this - have you added silk to your url patterns?

**Comment by mtford90** [comment]
Also - which django version?

**Comment by a1Gupta** [comment]
yes I did and I am using Django 1.7.7

**Comment by zahlio** [comment]
We are also having this issue, using Django 1.8.

**Comment by ElSaico** [comment]
I faced this as well; although the docs imply otherwise, seems like its endpoints are not optional. Just imported them into my `urls.py` and it worked again.

**Comment by avelis** [comment]
@ElSaico Can you point to me where in the docs it says app's endpoints are optional. Maybe a result of this issue is to change the expectation for proper installation.

**Comment by matthewhegarty** [comment]
Also seeing this on 1.11.1 - is there a fix or workaround?

**Comment by avelis** [comment]
@matthewhegarty What version of Django are you using? I wonder if the url patterns needs to be re-assessed with a configuration checker on config initialization.

**Comment by matthewhegarty** [comment]
Django version 1.11.1

**Comment by mark-adams** [comment]
@avelis Looks like #86 resolves this issue.

**Comment by lmiguelvargasf** [comment]
I am getting the same issue when running tests with pytest:
* django-silk 1.11.12
* python 3.6.5

**Comment by tprestegard** [comment]
I had this issue with running unit tests in Django 1.11.14 and python 2.7.13.  I found that it occurred because I have different settings files for production and test servers and only want the **test** servers to use silk.  I also only wanted to add the silk urlpatterns on test servers, which I handled by implementing an `if settings.DEBUG=True:` statement in urls.py that contained the silk urlpatterns.  I had done something similar for Django Debug Toolbar in the past.

However, it seems that running unit tests in Django sets `settings.DEBUG=False` automatically, overriding the global settings.  So my configuration resulted in the silk urlpatterns not being added when unit tests were run, and caused this error to be generated.

My problem was solved by adding the `--debug-mode` flag when running unit tests, or alternatively, by checking for some requirement other than `settings.DEBUG = True` in urls.py, like `'silk' in settings.INSTALLED_APPS`.  However, I still suggest to merge the fix in #86 or do something similar.  As far as I can tell, the `fpath` variable does not appear to be used anywhere else in this package, and along with this, doing a compile-time reverse does not seem like the best practice.

**Comment by xahin96** [comment]
@tprestegard I am also facing the same issue! How do I run pytest in DEBUG MODE ?

**Comment by tprestegard** [comment]
@xahin96 I'm not sure whether that's possible. I ended up just doing the check like `if 'silk' in settings.INSTALLED_APPS` rather than `if not settings.DEBUG` since `silk` was only in `settings.INSTALLED_APPS` in my test settings.

I see that #86 was merged since my previous post, so I would think this is fixed in a more recent version of this package, but I can't say for certain from personal experience.  If so, this issue could potentially be closed.
